.gitignore
Dockerfile
README.md
docker-compose.yaml
main.go

Add docker and docker-compose support

docker support

---

docker-compose.yaml
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/proxy/response.go
scripts/goproxy.service
scripts/index.html

fix (latest & list)

---

build/generate.sh
circle-test.sh

get `${GOROOT}` by `go` toolchain

fix generate failed 

---

.circleci/config.yml
Dockerfile
Makefile
circle-test.sh
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
test/get_test.sh
test/testdata/get.txt

1. resolve package-path contains subdir path
2. add test
3. adjust build

fix(subpath) & test

---

pkg/proxy/proxy.go

We should allow users to list dir via a browser.

always provide file serve

---

.circleci/config.yml
pkg/proxy/proxy.go

fix cache issue

---

test/testdata/get.txt

add more tests

---

.gitignore
pkg/proxy/proxy.go
pkg/proxy/response.go

fix go get failed in go1.13beta1

---

.circleci/config.yml

add tests for router mode

---

main.go
proxy/router.go

use path.Match instead of regexp

---

README.md
proxy/router.go

all direct when empty proxy
all proxy when empty exclude

fix empty exclude

---

README.md

we can describe make with more detail

Update README.md, describe how to make with more detail

---

main.go
proxy/router.go

Fixes #106 
Take the same action as in `server.go`.
Took advantage to run `gofmt` in the project too.

proxy/router: fix panic & gofmt

---

proxy/router.go

proxy/router: respect http proxy environment variables

---

main.go

* Handle os signaling to make graceful shutdown. This means waiting for current requests to finish before killing the web server, this might prevent nasty bugs as a consequence of the process being killed.
* All the logic to get `downloadRoot` was extracted to a function since the `main` was getting too long, and can be encapsulated.
* Notice other slight change: in `downloadRoot` if `if cacheDir != ""`, it will return immediately. Before this change, it would continue getting again the `GOPATH` env var, to again assign `downloadRoot` to the same, reconstructed, original value. I mention this because I found it weird.

graceful shutdown & refactor improvements

---

main.go

remove repeated sigterm signal

remove repeated signal

---

main.go
proxy/router.go

fix file mode 

---

main.go

Proxy mode cacheDir was unused. 
set the downloadRoot  when init.

Fix cacheDir  is not in effect

---

.circleci/config.yml
proxy/router.go
renameio/renameio.go
renameio/renameio_test.go
renameio/umask_test.go
robustio/robustio.go
robustio/robustio_other.go
robustio/robustio_windows.go

renameio.WriteFile writes files atomically by renaming temporary files

---

main.go

Auto enable go module

---

proxy/router.go

Reverts goproxyio/goproxy#153
Fixes #155

Revert "[patch] allow caching it when http response code 302 is got from upst…"

---

main.go
proxy/router.go

fix: support cache 302 status code

---

test/testdata/get.txt

test: add a new test case

---

main.go
proxy/router.go

feat: support to set cache expiration

---

sumdb/handler.go
sumdb/handler_test.go

1. remove the posible infinite loop #202 
2. add timeout for `http.Get` https://github.com/goproxyio/goproxy/blob/e03dc0f0bf84ec8ea486c6976e966dc3038772d3/sumdb/handler.go#L69
3. remove some risk, like `curl -v https://goproxy.io/sumdb/www.google.com`

change sumdb proxy impl
